//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mascotas
    {
        public int id { get; set; }
        public string nombre_Mascota { get; set; }
        public int idDueño { get; set; }
        public int idDireccion { get; set; }
        public int idHClinica { get; set; }
        public string Animal { get; set; }
        public string Raza { get; set; }
    }
}
